name: Test Job

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: cd && echo hello > ./hello
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: cd && cat ./hello
